### ISSUE TITLE
Context to the readme?

### ISSUE THREAD

**Issue by cboettig** [traitecoevo/baad.data#1]
@richfitz thanks for sharing, I really like this approach.

While presumably most people will come to this repo by way of the paper rather than the other way around, it would be nice to state what kind of data 'baad' contains in the README and repository description.  (We're trying to remedy the same problem with a lot of ropensci readmes that are equally opaque, particularly whenever the database in question is some acronym).  A link to your Ecology paper would likewise be handy (though I guess if it's not open access that may be less convenient for some as a way of documenting what's going on here).

**Comment by wcornwell** [comment]
Hey @cboettig this and https://github.com/wcornwell/TaxonLookup were our attempt at devising a semantic versioning system for living datasets within R that makes it easy for people to use the different versions of the dataset easily.  Have you seen anyone else do this?  Are there any other models out there?

**Comment by dfalster** [comment]
@richfitz @wcornwell Great work coming up with this approach, really useful. I've been wondering for a couple of years how one could quickly access different versions of data.  

Would e nice if a single master DOI could also support different versions, e.g by adding version number at the end. Anyone know of a data provider supporting this feature?

**Comment by wcornwell** [comment]
http://wiki.datadryad.org/DOI_Usage

Looks like it's possible in theory. Not sure how it works in practice...
Guess we'll find out..

**Comment by cboettig** [comment]
@wcornwell @dfalster @richfitz Versioning DOIs is perhaps not as trivial as it seems.  You might find [this thread](https://groups.google.com/forum/#!searchin/dryad-dev/dataset$20versions/dryad-dev/luS0kTWas6s/BpvfvCf8UNgJ) from the dryad-dev list to be of interest.  

As @mfenner points out there, technically DOIs are not versioned; that's just a Dryad convention; and not the current one; since DataONE wants DOIs to point to immutable objects rather than the 'latest version'.  That thread also recommends that version relationships be captured in metadata explicitly, rather than only by convention. 

Seems like there are several unsolved issues in how to do this, but the recommendation is to use the timestamp as a URL query parameter after the DOI (e.g.  http://dx.doi.org/10.5061/dryad.82t1k/1?ver=2014-02-10T13:01:02.328-05:00), rather than something that looks like DOI but isn't registered, as @mbjones points out.

**Comment by mbjones** [comment]
We've discussed versioning ad nauseum in DataONE. Its not easy across institutions, as every group makes their own sensible decisions at a point in time and then tends to stick to that, but over time it creates significant heterogeneity.  My perspective:
- Identifier standards change over time, so we expect identifier syntax to shift (continuously) over 5-10 years; identifier syntax is ephemeral, so we just treat them as strings in DataONE; in the wild we find objects with identifiers that are locally-scoped strings, UUIDs (bare, or in urn:uuid: and uuid: schemes), LSIDs, LSRNs, ARKs, ISBNs, HTTP URIs, HTTPS URIs, other URIs, DOIs (registered, and unregistered, with scheme doi: or several http schemes), Handles, ISSNs, etc.  See the list of [DataCite identifier types](http://www.essepuntato.it/lode/http://purl.org/spar/datacite#namedindividuals).
  - Example: these all resolve as same DOI using various string variants: `10.5063/F1VX0DF9`, `doi:10.5063/F1VX0DF9`, `http://doi.org/doi:10.5063/F1VX0DF9`, `http://doi.org/10.5063/F1VX0DF9`, `http://dx.doi.org/doi:10.5063/F1VX0DF9`, `http://dx.doi.org/10.5063/F1VX0DF9`, `https://doi.org/doi:10.5063/F1VX0DF9`, `https://doi.org/10.5063/F1VX0DF9`, `https://dx.doi.org/doi:10.5063/F1VX0DF9`, `https://dx.doi.org/10.5063/F1VX0DF9`, `http://dx.doi.org/doi:10.5063/F1VX0DF9`, `https://dx.doi.org/doi:10.5063/F1VX0DF9`, `https://dx.doi.org/doi:10.5063/F1VX0DF9?v=3`, `https://dx.doi.org/doi:10.5063/F1VX0DF9?ts=2010-05-01T12:34:32.12Z`, etc.
  - If one asked for the data associated with `https://dx.doi.org/doi:10.5063/F1VX0DF9?v=3` and `https://dx.doi.org/doi:10.5063/F1VX0DF9?ts=2010-05-01T12:34:32.12Z`, based on the DOI standard I would not know whether to expect those to be 'the same' data objects or not -- they resolve as the same DOI, but its unclear what else is going on in the query params. In DataONE, we choose to treat all unique identifier strings as unique identifiers as part of our [DataONE identifier interoperability guidelines](https://releases.dataone.org/online/api-documentation-v1.2.0/design/PIDs.html). 
- Most identifier standards don't explicitly encode version semantics, and generally recommend that identifiers be opaque; there's no agreement on how to encode version info in identifiers, only local conventions
- Therefore, version relationships should be expressed in metadata, using predicates such as [`prov:wasDerivedFrom`](http://www.w3.org/TR/2013/REC-prov-o-20130430/#wasDerivedFrom) and [`prov:wasVersionOf`](http://www.w3.org/TR/2013/REC-prov-o-20130430/#wasRevisionOf), which are both highly understandable and interoperable across institutions because of their explicit semantics.
